spring:
  profiles:
    active: prod
  flyway:
    enabled: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG