server:
  port: 7777

spring:
  profiles:
    active: dev
  flyway:
    enabled: false
  security:
    user:
      name: pawel
      password: abc123

  main:
    allow-bean-definition-overriding: true

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG