spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing-jpa
    username: postgres
    password: kazan
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoices:
  database: jpa