package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.futurecollars.invoicing.db.WithId;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
public class Company implements WithId {

    @ApiModelProperty(value = "Company id (generated by application", required = true, example = "1")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private long id;

    @ApiModelProperty(value = "Tax identification number", required = true, example = "555-555-55-55")
    private String taxIdentificationNumber;

    @ApiModelProperty(value = "Company address", required = true, example = "Mazowiecka 134, 32-525, Radzionków")
    private String address;

    @ApiModelProperty(value = "Company name", required = true, example = "Invoice House Ltd.")
    private String name;

    @ApiModelProperty(value = "Value of health insurance", required = true, example = "319.94")
    private BigDecimal healthInsurance;

    @ApiModelProperty(value = "Value of pension insurance", required = true, example = "514.57")
    private BigDecimal pensionInsurance;

}
