package pl.futurecollars.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
public class InvoiceEntry {

    @JsonIgnore
    @ApiModelProperty(value = "Invoice entry id (generated by application", required = true, example = "1")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private long id;
    @ApiModelProperty(value = "Product/service description", required = true, example = "Dell x12 v3")
    private String description;
    @ApiModelProperty(value = "Number of items", required = true, example = "85")
    private BigDecimal quantity;
    @ApiModelProperty(value = "Product/service net price", required = true, example = "1857.15")
    private BigDecimal price;
    @ApiModelProperty(value = "Product/service vat value", required = true, example = "0")
    private BigDecimal vatValue;
    @Enumerated(EnumType.STRING)
    @ApiModelProperty(value = "Tax rate", required = true, example = "VAT_0")
    private Vat vatRate;
    @JoinColumn(name = "car_in_private_use")
    @ApiModelProperty(value = "Information whether car is also used for privat purposes", required = true, example = "true")
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
    private Car carInPrivateUse;
}
